Use vendored rhsm_repository_release module
oasis-roles/rhsm pull request #15
Opened 2018-12-06 21:26 UTC by seandst

closes #10 

See #10 for details.

2018-12-06 22:40 UTC, robled requested changes

2018-12-06 22:40 UTC, robled commented on README.md
> +* `rhsm_release` - Set which operating system release version to use. Remember to quote this for release version that look like
version(s)?

2018-12-07 15:58 UTC, seandst commented on README.md
> +* `rhsm_release` - Set which operating system release version to use. Remember to quote this for release version that look like
deeeeeeeerp

2018-12-07 18:31 UTC, robled approved these changes

2018-12-07 18:31 UTC, merged