Add "pool" option and update gitignore
oasis-roles/rhsm pull request #5
Opened 2018-06-18 20:06 UTC by andrew103

Added the rhsm "pool" option where necessary and updated the .gitignore file to exclude the symlink

2018-06-18 20:08 UTC, oasis-automation commented
Can one of the admins verify this patch?

2018-06-18 21:17 UTC, greg-hellings approved these changes

2018-06-20 11:46 UTC, tehsmyers requested changes

2018-06-20 11:46 UTC, seandst commented on .gitignore
> +basic_subscription
This is a downstream component; upstream should have no knowledge of downstream. Please remove it.

2018-06-20 11:46 UTC, seandst commented on README.md
> +* `rhsm_pool` - specific pool name to consume (regex can be used as input)
The admonition from the [redhat_subscrition](https://docs.ansible.com/ansible/latest/modules/redhat_subscription_module.html) module docs should probably be included here: "Use pool_ids instead if possible, as it is much faster." Additionally, `rhsm_pools` needs to indicate that it is now mutually exclusive with `rhsm_pool_ids`, and `rhsm_pool_ids` needs to indicate that it is now mutually exclusive with `rhsm_pools`

2018-06-20 17:17 UTC, seandst commented
ok build

2018-06-20 18:15 UTC, tehsmyers approved these changes

2018-06-20 18:15 UTC, seandst commented
Passed super-secret downstream CI

2018-06-20 18:15 UTC, merged